export const carBrands: Array<string> = [
    'Toyota',
    'Honda',
    'Ford',
    'Chevrolet',
    'Volkswagen',
    'Nissan',
    'BMW',
    'Mercedes-Benz',
    'Audi',
    'Lexus',
    'Hyundai',
    'Kia',
    'Subaru',
    'Mazda',
    'Tesla',
];

export const carModels: Array<string> = [
    'Corolla',
    'Civic',
    'F-150',
    'Camaro',
    'Golf',
    'Altima',
    '3 Series',
    'E-Class',
    'A4',
    'RX',
    'Elantra',
    'Sorento',
    'Outback',
    'CX-5',
    'Model S',
];
